WIKIPEDIA_TOPICS = [
    "Large language model",
    "Transformer (machine learning model)",
    "Generative adversarial network",
    "Diffusion model",

    "Reinforcement learning from human feedback",
    "Model drift",
    "Federated learning",
    "Explainable artificial intelligence",
    "AI safety",

    "Multimodal learning",
    "Graph neural network",
    "Neural architecture search",

    "Ethics of artificial intelligence",
    "Regulation of artificial intelligence",

    "Reasoning language model",
    "Small language model",
    "Agentic AI",
    "LLM agent",
    "Language model benchmark",
    "Retrieval-augmented generation",
    "Direct preference optimization",
    "Reinforcement learning from AI feedback",
    "Constitutional AI",
    "Model collapse",
    "Waluigi effect",
    "AI bubble",
    "AI washing",
    "Text watermarking",
    "Artificial intelligence content detection",
    "Prompt injection",
    "Adversarial machine learning",
    "Vector database",

    "Model Context Protocol",
    "Open-source artificial intelligence",
    "Neural processing unit",
    "Tensor Processing Unit",
    "Blackwell (microarchitecture)",

    "Artificial Intelligence Act",
    "European Artificial Intelligence Office",
    "Executive Order 14110",
    "AI Safety Institute",
    "AI Safety Summit",
    "Safe and Secure Innovation for Frontier Artificial Intelligence Models Act",
    "National Security Memorandum on Artificial Intelligence",

    "LMArena",

    "GPT-4o",
    "OpenAI o1",
    "OpenAI o3",
    "Llama (language model)",
    "Gemma (language model)",
    "Qwen",
    "Claude (language model)",
    "Gemini (language model)",
    "Grok (chatbot)",
    "DeepSeek",

    "Sora (text-to-video model)",
    "Veo (text-to-video model)",
    "Dream Machine (text-to-video model)",
    "Neural radiance field",
    "Gaussian splatting",

    "Vision transformer",
    "Diffusion model",
    "Flow-based generative model",

    "AI alignment",
    "P(doom)",
    "Hallucination (artificial intelligence)",

    "LangChain",
    "Llama.cpp",

    "History of artificial intelligence",
    "Timeline of artificial intelligence",
    "AI boom",
    "AI winter",
    "AI bubble",
    "Dartmouth workshop",
    "History of machine translation",
    "History of artificial life",
    "AI@50",
    "Lighthill report",
    "ALPAC report",
    "Fifth Generation Computer Systems",
    "Strategic Computing Initiative",
    "Deep Blue versus Kasparov, 1997, Game 6",
    "AlphaGo versus Lee Sedol",

    "Philosophy of artificial intelligence",
    "Turing test",
    "Computing Machinery and Intelligence",
    "Chinese room",
    "A Logical Calculus of the Ideas Immanent in Nervous Activity",
    "Hard problem of consciousness",
    "Computationalism",
    "Functionalism (philosophy of mind)",
    "Symbolic AI",
    "Physical symbol system",
    "Dreyfus' critique of AI",
    "Neat vs. scruffy",
    "Soft vs. hard computing",
    "Connectionism",
    "AI welfare and rights",
    "Robot rights",
    "Artificial consciousness",

    "Artificial intelligence",
    "Outline of artificial intelligence",
    "Glossary of artificial intelligence",
    "Artificial general intelligence",
    "Narrow AI",
    "Superintelligence",
    "Technological singularity",
    "Transhumanism",
    "Knowledge representation",
    "Ontology (information science)",
    "Commonsense knowledge",
    "Frame problem",
    "Reasoning",
    "Automated reasoning",
    "Probabilistic methods for uncertain reasoning",
    "Decision theory",
    "Game theory",
    "Search algorithm",
    "State space search",
    "Heuristic",
    "Mathematical optimization",
    "Machine perception",
    "Intelligent agent",

    "Machine learning",
    "Artificial neural network",
    "Neural network (machine learning)",
    "Connectionism",
    "Perceptron",
    "Hebbian theory",
    "Backpropagation",
    "Activation function",
    "Loss function",
    "Loss functions for classification",
    "Gradient descent",
    "Stochastic gradient descent",
    "Learning rate",
    "Hyperparameter (machine learning)",
    "Overfitting",
    "Normalization (machine learning)",
    "Weight initialization",

    "Deep learning",
    "Feedforward neural network",
    "Recurrent neural network",
    "Long short-term memory (LSTM)",
    "Gated recurrent unit (GRU)",
    "Convolutional neural network",
    "U-Net",
    "Residual neural network",
    "Autoencoder",
    "Variational autoencoder",
    "Generative adversarial network",
    "Deep belief network",
    "Spiking neural network",
    "Graph neural network",

    "Transformer (machine learning model)",
    "Attention (machine learning)",
    "Large language model",
    "Foundation model",
    "Generative pre-trained transformer (GPT)",
    "Word embedding",

    "Mixture of experts",
    "Sparsely-gated MoE layer",
    "Hierarchical temporal memory",
    "Neural architecture search",
    "Neuroevolution",
    "Dilution (neural networks)",
    "Hidden layer",
    "Gating mechanism",
    "Model compression",
    "Knowledge distillation",
    "Lottery ticket hypothesis",
    "Neural scaling law",
    "Physics-informed neural networks",
    "Topological deep learning",

    "Generative artificial intelligence",
    "Foundation model",
    "Large language model",
    "OpenAI Models",
    "GPT-5",
    "GPT-4.5",
    "GPT-4.1",
    "OpenAI o3",
    "OpenAI o4-mini",
    "OpenAI Operator",
    "ChatGPT Deep Research",
    "DeepSeek Models",
    "DeepSeek (chatbot)",
    "DeepSeek-R1",
    "DeepSeek-V3",
    "Anthropic Models",
    "Claude (language model)",
    "Claude 4",
    "Google Models",
    "Gemini (language model)",
    "Veo (text-to-video model)",
    "Veo 3",
    "Stargate LLC",
    "Manus (AI agent)",
    "Kruti",
    "Six Little Dragons",

    "Prompt engineering",
    "Retrieval-augmented generation (RAG)",
    "Chain-of-thought prompting",
    "In-context learning (natural language processing)",
    "Fine-tuning (deep learning)",
    "Reinforcement learning from human feedback (RLHF)",
    "Constitutional AI",
    "Diffusion model",
    "Latent diffusion model",
    "Text-to-image generation",
    "Text-to-video generation",
    "Hallucination (artificial intelligence)",
    "Knowledge cutoff",

    "Language model benchmark",
    "Progress in artificial intelligence",
    "Humanity's Last Exam",
    "MMMU (Massive Multi-discipline Multimodal Understanding)",
    "GPQA (Graduate-Level Google-Proof Q&A)",
    "SWE-bench",
    "Chatbot Arena",
    "MT-Bench",
    "HELM Safety (Holistic Evaluation of Language Models)",
    "AIR-Bench",
    "FACTS",
    "Abstraction and Reasoning Corpus (ARC)",

    "Soup-of-Experts",
    "Kolmogorov-Arnold Networks",
    "Mamba (deep learning architecture)",
    "Byte Latent Transformer",
    "Self-Play Reinforcement Learning",
    "Deep reinforcement learning",
    "Multi-agent reinforcement learning",
    "Model-Based Reinforcement Learning with Transformer World Models",
    "Bayesian Knowledge Distillation (BayesKD)",
    "Mixture of Experts Pruning",
    "Adaptive Data Optimization",
    "Self-Guided Direct Preference Optimization (SGDPO)",
    "Scaling Laws for LLM Fine-Tuning",
    "Mechanisms of Projective Composition of Diffusion Models",
    "Training Dynamics Underlying Language Model Scaling Laws",
    "Mechanistic Interpretability",
    "AI for Accelerated Materials Discovery (AI4Mat)",
    "Multi-domain Distribution Learning for De Novo Drug Design",

    "MLINGCONF: Multilingual Confidence Estimation on Large Language Models",
    "M-REWARDBENCH: Evaluating Reward Models in Multilingual Settings",
    "MPO: Multilingual Safety Alignment via Reward Gap Optimization",
    "Akan Cinematic Emotions (AkaCE) Dataset",
    "Derailer-Rerailer: Adaptive Verification for Efficient and Reliable Language Model Reasoning",
    "Natural Language Reasoning in Large Language Models: Analysis and Evaluation",
    "How Numerical Precision Affects Arithmetical Reasoning Capabilities of LLMs",
    "Data Caricatures: On the Representation of African American Language in Pretraining Corpora",
    "Translate With Care: Addressing Gender Bias, Neutrality, and Reasoning in LLMs",
    "Unintended Harms of Value-Aligned LLMs",
    "VITAL: A New Dataset for Benchmarking Pluralistic Alignment in Healthcare",
    "Persona-Aware LLM-Enhanced Framework for Multi-Session Personalized Dialogue",
    "Exploring In-Image Machine Translation with Real-World Background",
    "DALR: Dual-level Alignment Learning for Multimodal Sentence Representation",
    "GOLFer: Hallucination Filtering for Query Expansion",
    "TokAlign: Efficient Vocabulary Adaptation via Token Alignment",

    "Embodied Computer Vision",
    "RoboBallet",
    "RoBoSpatial: A Benchmark for Spatial Reasoning in Robotics",
    "GROVE: Generalized Reward Learning with Vision-Language Prompts",
    "Navigation World Models",
    "Gemini Robotics: Bringing AI to the Physical World",
    "VGGT: Visual Geometry Grounded Transformer",
    "Neural radiance field",
    "Gaussian splatting",
    "3D from multi-view and sensors",
    "Vision-language-action model",
    "Mobile Diffusion for Video Editing",
    "Green Diffusion",

    "Artificial intelligence in healthcare",
    "AI for disease detection and diagnosis",
    "Interpreting brain scans",
    "AI for spotting bone fractures",
    "Deep learning in photoacoustic imaging",
    "Clinical decision support system",
    "Predicting adverse events in acute care",
    "Drug discovery",
    "AlphaFold",
    "Ayurgenomics",
    "AI for healthcare administration",
    "Microsoft Dragon Copilot",
    "AI for notetaking",
    "Retrieval-Augmented Generation in clinical chatbots (ChatRWD)",
    "Detecting early signs of disease (AstraZeneca model)",
    "Assessing ambulance needs",
    "AI and traditional medicine",

    "Artificial intelligence in finance",
    "Algorithmic trading",
    "Portfolio optimization",
    "Artificial intelligence in fraud detection",
    "Customer service",
    "Sales and marketing",
    "Enterprise knowledge systems",

    "Robotics",
    "Autonomous car",
    "Self-driving cars",
    "Waymo",
    "Baidu Apollo Go",
    "Simultaneous localization and mapping (SLAM)",
    "Multi-robot orchestration (RoboBallet)",
    "Automation in construction",

    "AI for mathematics and computer science",
    "AlphaEvolve",
    "AlphaDev",
    "AlphaTensor",
    "AlphaCode",
    "AI for physics and chemistry",
    "GNoME (Graph Networks for Materials Exploration)",
    "AI for climate and sustainability",
    "WeatherNext",
    "Data-driven astronomy",

    "Generative art",
    "Synthetic media",
    "Deepfake",
    "Audio deepfake",
    "Text-to-image models",
    "DALL-E",
    "Midjourney",
    "Stable Diffusion",
    "Text-to-video models",
    "Sora (text-to-video model)",
    "Veo (text-to-video model)",
    "Text-to-music models",
    "MusicLM",
    "Video content analysis",
    "Game artificial intelligence",
    "AlphaGo",
    "AlphaStar (software)",
    "OpenAI Five",
    "MuZero",

    "OpenAI",
    "Google DeepMind",
    "Anthropic",
    "Meta AI",
    "DeepSeek",
    "Mistral AI",
    "Stability AI",
    "Cognition AI",
    "Scale AI",
    "Stanford Institute for Human-Centered AI (HAI)",
    "Allen Institute for AI",
    "Machine Intelligence Research Institute",
    "Center for AI Safety",
    "Center for Human-Compatible Artificial Intelligence",
    "Future of Life Institute",
    "Algorithmic Justice League",
    "MIT Computer Science and Artificial Intelligence Laboratory",
    "Association for the Advancement of Artificial Intelligence (AAAI)",
    "Confederation of Laboratories for Artificial Intelligence Research in Europe (CLAIRE)",
    "European Association for Artificial Intelligence",

    "Hugging Face",
    "Kaggle",
    "OpenCog",
    "EleutherAI",
    "List of artificial intelligence projects",
    "List of datasets for machine-learning research",
    "ImageNet",
    "The Stargate Project",

    "AI accelerator",
    "Graphics processing unit (GPU)",
    "Tensor processing unit (TPU)",
    "Neural processing unit (NPU)",
    "Nvidia",
    "Lisp machine",
    "Cloud computing",

    "TensorFlow",
    "PyTorch",
    "JAX (software)",
    "Keras",
    "scikit-learn",
    "Microsoft Cognitive Toolkit (CNTK)",
    "Apache MXNet",
    "MLX (Apple)",
    "MLOps (Machine Learning Operations)",
    "Automated machine learning (AutoML)",
    "ModelOps",
    "Artificial intelligence optimization (AIO)",
    "Google Colab",
    "Weka (machine learning)",
    "Open Neural Network Exchange (ONNX)",

    "Ethics of artificial intelligence",
    "AI safety",
    "Explainable artificial intelligence (XAI)",
    "Algorithmic bias",
    "Fairness (machine learning)",
    "Stochastic parrot",
    "Hallucination (artificial intelligence)",
    "Misinformation",
    "Deepfake",
    "Technological unemployment",
    "Existential risk from artificial general intelligence",
    "Privacy and copyright",
    "Intellectual property issues in AI",
    "Likeness and impersonation",

    "Regulation of artificial intelligence",
    "AI Act (European Union)",
    "DEFIANCE Act (United States)",
    "AI Action Summit",
    "Spanish Agency for the Supervision of Artificial Intelligence",
    "Trustworthy AI",
    "Responsible AI",
    "AI alignment",

    "Applications of artificial intelligence",
    "Environmental impact of artificial intelligence",
    "Dominance by tech giants",
    "Artificial Intelligence Cold War",
    "Weaponized AI",
    "AI in fiction"
]
